name = "secretshare-dev"name = "${WORKER_NAME}"

main = "src/worker.ts"main = "src/worker.ts"

compatibility_date = "2024-01-01"compatibility_date = "2024-01-01"

workers_dev = trueworkers_dev = true

account_id = "${CLOUDFLARE_ACCOUNT_ID}"

# KV Namespaces - Update these with your actual KV namespace IDs

kv_namespaces = [# KV Namespaces

  { binding = "SECRETS_KV", preview_id = "your-preview-kv-id", id = "your-dev-kv-id" }kv_namespaces = [

]  { binding = "SECRETS_KV", preview_id = "${KV_NAMESPACE_PREVIEW_ID}", id = "${KV_NAMESPACE_ID}" }

]

# Environment Variables (non-sensitive)

[vars]# Environment Variables (non-sensitive)

ALLOWED_ORIGINS = "http://localhost:8787,https://your-dev-worker.workers.dev"[vars]

ALLOWED_ORIGINS = "${ALLOWED_ORIGINS}"

# Production environment (configured via GitHub Actions)

[env.production]# Production environment

name = "secretshare-prod"[env.production]

workers_dev = falsename = "${WORKER_NAME}-prod"

workers_dev = false

[env.production.vars]

ALLOWED_ORIGINS = "https://your-domain.com"[env.production.vars]

ALLOWED_ORIGINS = "${ALLOWED_ORIGINS_PROD}"

# Staging environment (configured via GitHub Actions)

[env.staging]# Staging environment

name = "secretshare-staging"[env.staging]

kv_namespaces = [name = "${WORKER_NAME}-staging"

  { binding = "SECRETS_KV", id = "your-staging-kv-id" }kv_namespaces = [

]  { binding = "SECRETS_KV", id = "${KV_NAMESPACE_STAGING_ID}" }

]

[env.staging.vars]

ALLOWED_ORIGINS = "https://staging.your-domain.com"[env.staging.vars]
ALLOWED_ORIGINS = "${ALLOWED_ORIGINS_STAGING}"