# Simple Cloudflare Worker Configuration for SecretShare
name = "secretshare"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# Static site configuration - serves files from public/ directory
[site]
bucket = "./public"

# KV Namespace for storing secrets (replace with actual IDs)
# Production values will be overridden via Cloudflare Dashboard
[[kv_namespaces]]
binding = "SECRETS_KV"
preview_id = "your-preview-kv-namespace-id"
id = "your-production-kv-namespace-id"

# Environment variables (these can be overridden in Cloudflare Dashboard)
[vars]
# CORS origins - override in Dashboard for production
ALLOWED_ORIGINS = "http://localhost:8787"
# CSRF secret - MUST be overridden in Dashboard for production
CSRF_SECRET = "dev-secret-change-for-production"