name = "secretshare-dev"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
workers_dev = true

# Static file serving configuration
[site]
bucket = "./public"

# KV Namespaces - Update these with your actual KV namespace IDs
kv_namespaces = [
  { binding = "SECRETS_KV", preview_id = "your-preview-kv-id", id = "your-dev-kv-id" }
]

# Environment Variables (non-sensitive)
[vars]
ALLOWED_ORIGINS = "http://localhost:8787,https://your-dev-worker.workers.dev"

# Production environment (configured via GitHub Actions)
[env.production]
name = "secretshare-prod"
workers_dev = false

[env.production.vars]
ALLOWED_ORIGINS = "https://your-domain.com"

# Staging environment (configured via GitHub Actions)
[env.staging]
name = "secretshare-staging"
kv_namespaces = [
  { binding = "SECRETS_KV", id = "your-staging-kv-id" }
]

[env.staging.vars]
ALLOWED_ORIGINS = "https://staging.your-domain.com"

kv_namespaces = [name = "${WORKER_NAME}-staging"

  { binding = "SECRETS_KV", id = "your-staging-kv-id" }kv_namespaces = [

]  { binding = "SECRETS_KV", id = "${KV_NAMESPACE_STAGING_ID}" }

]

[env.staging.vars]

ALLOWED_ORIGINS = "https://staging.your-domain.com"[env.staging.vars]
ALLOWED_ORIGINS = "${ALLOWED_ORIGINS_STAGING}"